name = "file-uploader"
compatibility_date = "2024-09-09"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Bind an R2 Bucket. Use R2 to store arbitrarily large blobs of data, such as files.
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#r2-buckets
[[r2_buckets]]
binding = "R2"
bucket_name = "gregskril"

# The necessary secrets are:
# - ADMIN_SECRET
# Run `echo <VALUE> | npx wrangler secret put <NAME>` for each of these
